# Taps

# CLI Tools - General Utilities & Power User Tools
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "coreutils"
brew "fastfetch"
brew "gh"
brew "git"
brew "gnupg"
brew "htop"
brew "lsd"
brew "lzip"
brew "mac-cleanup-py"
#brew "mas"
brew "mkdocs"
brew "moreutils"
brew "most"
brew "nano"
brew "nanorc"
brew "ncdu"
brew "nethogs"
brew "nmap"
brew "openssh"
brew "osx-cpu-temp"
brew "pandoc"
brew "paperkey"
brew "pinentry-mac"
brew "pwgen"
brew "qemu"
brew "qrencode"
brew "rclone"
brew "speedtest-cli"
brew "tealdeer"
brew "topgrade"
brew "trash"
brew "tree"
brew "watch"
brew "wget"
brew "zip"
brew "zsh"

# Repo essentials
brew "ripgrep"
brew "shellcheck"
brew "shfmt"

# Languages / runtimes
brew "node"
brew "nvm"
brew "python@3.11"
brew "python@3.12"
brew "pipx"
brew "pyenv"
brew "openjdk"

# CLI Tools - Media
brew "ffmpeg"
brew "chromaprint"    # Core component of the AcoustID project (Audio fingerprinting)
brew "sox"
brew "whisper-cpp"
brew "yt-dlp"

# Casks - General Applications & Utilities
cask "1password"
cask "1password-cli"
cask "4k-video-downloader+"
cask "a-better-finder-rename"
cask "adapter"
cask "aldente"
cask "appcleaner"
cask "arctic"
cask "audio-hijack"
cask "auto-claude"
cask "balenaetcher"
cask "brave-browser"
cask "calibre"
cask "chatgpt"
cask "claude"
cask "claude-code"
cask "cryptomator"
cask "cursor"
cask "descript"
cask "discord"
cask "disk-drill"
cask "dropbox"
cask "etrecheckpro"
cask "farrago"
cask "firefox"
cask "fission"
cask "flux-app"
cask "folx"
cask "github"
cask "google-chrome"
cask "google-chrome@canary"
cask "google-drive"
cask "gpg-suite-no-mail"
cask "hammerspoon"
cask "handbrake-app"
cask "helium-browser"
cask "hot"
cask "ilok-license-manager"
cask "iterm2"
cask "izotope-product-portal"
cask "joplin"
cask "jordanbaird-ice"
cask "keka"
cask "keybase"
cask "keyboardcleantool"
cask "kid3"
cask "kobo"
cask "loopback"
cask "losslesscut"
cask "macfuse"
cask "macwhisper"
cask "mdrp"
cask "mediainfo"
cask "minecraft"
cask "musicbrainz-picard"
cask "nordvpn"
cask "omnidisksweeper"
cask "onyx"
cask "openaudible"
cask "openmtp"
cask "piezo"
cask "pulsar"
cask "raspberry-pi-imager"
cask "raycast"
cask "samsung-magician"
cask "screenflow"
cask "shutter-encoder"
cask "signal"
cask "slack"
cask "soundsource"
cask "stats"
cask "steam"
cask "steinberg-download-assistant"
cask "subler"
cask "swift-publisher"
cask "the-unarchiver"
cask "timemachineeditor"
cask "typora"
cask "utm"
cask "veracrypt"
cask "vlc"
cask "waves-central"
cask "whatsapp"
cask "zoom"

# Mac App Store Apps
#mas "Amphetamine", id: 937984704
#mas "BetterSnapTool", id: 417375580
#mas "Blackmagic Disk Speed Test", id: 425264550
#mas "Chrono Plus", id: 946047238
#mas "Compressor", id: 424390742
#mas "Encrypto", id: 935235287
#mas "Final Cut Pro", id: 424389933
#mas "GarageBand", id: 682658836
#mas "Hush", id: 1664181766
#mas "iMovie", id: 408981434
#mas "Keynote", id: 409183694
#mas "Logic Pro", id: 634148309
#mas "NextDNS", id: 1464122853
#mas "Numbers", id: 409203825
#mas "Pages", id: 409201541
#mas "Parcel", id: 639968404
#mas "Pixelmator Pro", id: 1289583905
#mas "Pure Paste", id: 1611378436
#mas "Speedtest", id: 1153157709
